### ISSUE TITLE
Flick Large - Flick Demo doesn't work

### ISSUE THREAD

**Issue by RobertKrens** [jancalve/MMM-flick-gestures#1]
Good afternoon.

Configuring my mirror this is just "the" module I needed. 

The "pip install flicklib" gives the following data: 
```
pi@MagicMirror:~ $ sudo pip install flicklib
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: flicklib in /usr/local/lib/python2.7/dist-packages/flicklib-0.      0.3-py2.7.egg (0.0.3)
Requirement already satisfied: RPi.GPIO in /usr/lib/python2.7/dist-packages (from flicklib) (      0.7.0)
```
So It seems the Flick Libary is up to date. 

Running "i2cdetect -y -q 1" Shows: 
```
`     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f

00:          -- -- -- -- -- -- -- -- -- -- -- -- --

10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

40: -- -- 42 -- -- -- -- -- -- -- -- -- -- -- -- --

50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

70: -- -- -- -- -- -- -- --
`
```
Now I have a PIR sensor connected at GPIO21 (which works)
Also I've enabled I2C in the Raspi-Config

The Flick board powers up, but running the "pi@MagicMirror:~ $ ./flick-demo" command shows: 
```
`Did not receive firmware info
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "build/bdist.linux-armv7l/egg/flicklib.py", line 468, in _exit
TypeError: 'NoneType' object is not callable
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "build/bdist.linux-armv7l/egg/flicklib.py", line 468, in _exit
TypeError: 'NoneType' object is not callable
```
`

What am I missing? I anyone point me in a direction. 

Thanks in advance, 
Regards Robert

**Comment by RobertKrens** [comment]
Following this tutorial made me start de Flick-Demo:

http://wiringpi.com/wiringpi-updated-to-2-52-for-the-raspberry-pi-4b/

However, Touch, Tab and double tab work. Flick, Airwheel, and XYZ wont give any readings

Any help?

**Comment by RobertKrens** [comment]
Support call can be closed. Bought a new board, works perfect.
